name: "Develop Integration Tests"

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  integration_test:
    name: "Testes de Integração"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pytest pytest-cov

      - name: Terraform Tests
        working-directory: ./IAC
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Integration Tests
        working-directory: ./app
        run: |
          python -m pytest tests/integration/ --cov=.
          python main.py